--[[
	--- This is Wilson's speech file for Don't Starve Together ---
	Write your character's lines here. If you want to use another speech file as a base, get them from data\scripts\
	
	If you have the DLC and want custom lines for those, use a speech file from data\DLC0001\scripts instead.
	
	If you want to use quotation marks in a quote, put a \ before it.
	Example:
	"Like \"this\"."
]]
return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "Not a good idea. It's still up and about.",
			GENERIC = "I can't shave that.",
			NOBITS = "No more hair on this one.",
		},
		STORE =
		{
			GENERIC = "It's full.",
			NOTALLOWED = "I can't put that in there.",
			INUSE = "It's already in use. I guess I'll wait..",
		},
		RUMMAGE =
		{	
			GENERIC = "I can't do that.",
			INUSE = "It's already in use. I guess I'll wait..",	
		},
        COOK =
        {
            GENERIC = "I can't do that.",
            INUSE = "It's already in use. I guess I'll wait..",
        },
        GIVETOPLAYER = 
        {
        	FULL = "Come on. You can't even carry one more thing? Nnnaaa...",
    	},
    	GIVEALLTOPLAYER = 
        {
        	FULL = "I guess your pockets are full.",
    	},
	},
	ACTIONFAIL_GENERIC = "I can't do that.",
	ANNOUNCE_ADVENTUREFAIL = "Well that could have gone smoother. Naaa.",
	ANNOUNCE_BEES = "I should probably keep my distance from these.",
	ANNOUNCE_BOOMERANG = "Ow, a boomerang?!",
	ANNOUNCE_CHARLIE = "I wonder what that was.",
	ANNOUNCE_CHARLIE_ATTACK = "Ow- HEY! Something's biting me!",
	ANNOUNCE_COLD = "Getting a little chilly, nnnaaa...",
	ANNOUNCE_CRAFTING_FAIL = "I'm gonna need a few more things for that...",
	ANNOUNCE_DEERCLOPS = "Something big is heading right for us.",
	ANNOUNCE_DUSK = "It's getting dark.",
	ANNOUNCE_EAT =
	{
		GENERIC = "Not bad, nnnaaa~",
		PAINFUL = "Maybe I shouldn't have eaten that..",
		SPOILED = "Aha, wow, this is terrible!",
		STALE = "This food's spoiled. Oh well.",
	},
	ANNOUNCE_ENTER_DARK = "Nnnaaa... I can't see...",
	ANNOUNCE_ENTER_LIGHT = "Finally, some light.",
	ANNOUNCE_FREEDOM = "Naaa, I'm free!",
	ANNOUNCE_HIGHRESEARCH = "Interesting..",
	ANNOUNCE_HOUNDS = "Nnnnaa, that's a pretty scary sound.",
	ANNOUNCE_HUNGRY = "I could really go for some food right now.",
	ANNOUNCE_HUNT_BEAST_NEARBY = "Koalefant tracks. There must be one nearby.",
	ANNOUNCE_HUNT_LOST_TRAIL = "It ends here.",
	ANNOUNCE_INV_FULL = "Naa.. I don't think I have any more space for that.",
	ANNOUNCE_KNOCKEDOUT = "Nnnaaa, what happened?..",
	ANNOUNCE_LOWRESEARCH = "Well, that could have gone better.",
	ANNOUNCE_MOSQUITOS = "Nnaaa.. Stupid bugs..",
	ANNOUNCE_NODANGERSLEEP = "I don't feel safe, sleeping here.",
	ANNOUNCE_NODAYSLEEP = "I shouldn't waste anymore daylight than I have to..",
	ANNOUNCE_NODAYSLEEP_CAVE = "I'm not tired yet. Maybe I should keep going.",
	ANNOUNCE_NOHUNGERSLEEP = "Nnnnaaa.. Maybe I should eat something first...",
	ANNOUNCE_NODANGERAFK = "There's no point in fleeing now!",
	ANNOUNCE_NO_TRAP = "Fufufu. What a mediocre trap.",
	ANNOUNCE_PECKED = "Ow, get out of here! Dumb bird, nnaa..",
	ANNOUNCE_QUAKE = "An earthquake. I should be careful.",
	ANNOUNCE_RESEARCH = "Never enough knowledge...",
	ANNOUNCE_THORNS = "Nnnaa, prickly.",
	ANNOUNCE_TORCH_OUT = "I'm gonna need a new light..",
	ANNOUNCE_TRAP_WENT_OFF = "Nnaa, should have been more careful..",
	ANNOUNCE_UNIMPLEMENTED = "OW! I don't think it's ready yet.",
	ANNOUNCE_WORMHOLE = "Nnnaaa..",
	ANNOUNCE_CANFIX = "\nI might just be able to fix this..",
	ANNOUNCE_ACCOMPLISHMENT = "That wasn't so hard.",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "If only Mitty could see me now..",	
	ANNOUNCE_BECOMEGHOST = "Mittyy..",
	ANNOUNCE_GHOSTDRAIN = "Quite the familar feeling.. Nnah..",

	DESCRIBE_SAMECHARACTER = "N-nnaa, you're just like me?!",
	
	BATTLECRY =
	{
		GENERIC = "Nna, bad idea, taking me on!",
		PIG = "Get back here, swine!",
		PREY = "Easy pickings!",
		SPIDER = "I squish bugs like you all the time!",
		SPIDER_WARRIOR = "Better you than me!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "See? No problem.",
		PIG = "I'll let you go, this time..",
		PREY = "Stupid- Get back here!",
		SPIDER = "Nnnaa, spiders..",
		SPIDER_WARRIOR = "N-nna, good, it's gone..",
	},
	DESCRIBE =
	{
        PLAYER =
        {
            GENERIC = "It's %s.",
            ATTACKER = "Nnnaa.. I'm not sure I trust %s...",
            MURDERER = "I know what you've done!",
            REVIVER = "Quite the helpful soul, nnna~?",
            GHOST = "Poor soul, didn't stand a chance.",
        },
		WILSON = 
		{
			GENERIC = "It's Wilson.",
			ATTACKER = "Nnnaa.. I'm not sure I trust Wilson...",
			MURDERER = "I know what you've done!",
			REVIVER = "Quite the helpful soul, nnna~?",
			GHOST = "Poor soul, didn't stand a chance.",
		},
		WOLFGANG = 
		{
			GENERIC = "It's Wolfgang.",
			ATTACKER = "Nnnaa.. I'm not sure I trust Wolfgang...",
			MURDERER = "I know what you've done!",
			REVIVER = "Quite the helpful soul, nnna~?",
			GHOST = "Poor soul, didn't stand a chance.",
		},
		WAXWELL = 
		{
			GENERIC = "It's Maxwell!",
			ATTACKER = "Nnnaa.. I'm not sure I trust Maxwell...",
			MURDERER = "I know what you've done!",
			REVIVER = "Quite the helpful soul, nnna~?",
			GHOST = "Poor soul, didn't stand a chance.",
		},
		WX78 = 
		{
			GENERIC = "It's a robot.",
			ATTACKER = "Nnnaa.. I'm not sure I trust that robot...",
			MURDERER = "I know what you've done!",
			REVIVER = "Quite the helpful soul, nnna~?",
			GHOST = "Poor soul, didn't stand a chance.",
		},
		WILLOW = 
		{
			GENERIC = "It's Willow!",
			ATTACKER = "Nnnaa.. I'm not sure I trust Willow...",
			MURDERER = "I know what you've done!",
			REVIVER = "Quite the helpful soul, nnna~?",
			GHOST = "Poor soul, didn't stand a chance.",
		},
		WENDY = 
		{
			GENERIC = "It's Wendy!",
			ATTACKER = "Nnnaa.. I'm not sure I trust Wendy...",
			MURDERER = "I know what you've done!",
			REVIVER = "Quite the helpful soul, nnna~?",
			GHOST = "Poor soul, didn't stand a chance.",
		},
		WOODIE = 
		{
			GENERIC = "It's Woodie!",
			ATTACKER = "Nnnaa.. I'm not sure I trust Woodie...",
			MURDERER = "I know what you've done!",
			REVIVER = "Quite the helpful soul, nnna~?",
			GHOST = "Poor soul, didn't stand a chance.",
		},
		WICKERBOTTOM = 
		{
			GENERIC = "It's Wickerbottom!",
			ATTACKER = "Nnnaa.. I'm not sure I trust Wickerbottom...",
			MURDERER = "I know what you've done!",
			REVIVER = "Quite the helpful soul, nnna~?",
			GHOST = "Poor soul, didn't stand a chance.",
		},
		WES = 
		{
			GENERIC = "It's Wes.",
			ATTACKER = "Nnnaa.. I'm not sure I trust Wes...",
			MURDERER = "I know what you've done!",
			REVIVER = "Quite the helpful soul, nnna~?",
			GHOST = "Poor soul, didn't stand a chance.",
		},
		MULTIPLAYER_PORTAL = "This isn't like any relic I've seen before...",
		WORMLIGHT = "Hey, that doesn't look half bad.",
		WORM =
		{
		    PLANT = "Looks like an ordinary plant to me.",
		    DIRT = "A pile of dirt. Nnnna. Interesting.",
		    WORM = "Worms, we could learn a lot from the little guys.",
		},

		EEL = "Another ingredient for dinner, nnaa.",
		EEL_COOKED = "Nnnnaaaa~ I can't wait to dig in!",
		UNAGI = "Nna, almost as good as Riko. Sometimes I surprise even myself.",
		EYETURRET = "This thing looks kinda dangerous..",
		EYETURRET_ITEM = "I guess it's off.",
		MINOTAURHORN = "A big big horn. From a minotaur. Scary.",
		MINOTAURCHEST = "Maybe something useful is inside?",
		THULECITE_PIECES = "Thulecite. Lots and lots of little pieces of it.",
		POND_ALGAE = "Algae. Maybe I should scrape some up for later..",
		GREENSTAFF = "How in the world do I use this thing..",
		POTTEDFERN = "What a pretty plant.",

		THULECITE = "Mysterious materials. This sounds right up my alley, nnna~",
		ARMORRUINS = "This stuff is armor? Feels like I'm wearing nothing.",
		RUINS_BAT = "This thing's kinda heavy.. Reg could probably use this way more effectively than I can, nnaa..",
		RUINSHAT = "A crown?.. I've never seen anything like this before.",
		NIGHTMARE_TIMEPIECE =
		{
		CALM = "It seems things are fine for now.",
		WARN = "I certainly feel something, nnnaa..",
		WAXING = "Hey, this thing's getting a little intense!",
		STEADY = "Seems ballanced, for the moment.",
		WANING = "It feels like it's diminishing.",
		DAWN = "I guess the nightmare is running out!",
		NOMAGIC = "Doesn't feel like there's any magic around here.",
		},
		BISHOP_NIGHTMARE = "It's coming apart at the seams!",
		ROOK_NIGHTMARE = "Nnnaa, can't say I wanna stick around here much longer.",
		KNIGHT_NIGHTMARE = "It's a knightmare!",
		MINOTAUR = "Whatever that is, it doesn't look very happy to see me, nnnaa.",
		SPIDER_DROPPER = "Nnnnaaa, don't look up, don't look up..",
		NIGHTMARELIGHT = "I wonder who put this thing here.",
		GREENGEM = "Nnna, so pretty..",
		RELIC = "A Cave Raider's best friend. Not sure I'd be able to carry it back up with me, though, nnnaaa..",
		RUINS_RUBBLE = "Nnna, looks pretty broken to me.",
		MULTITOOL_AXE_PICKAXE = "Two useful tools in one. Yeah, I can use this..",
		ORANGESTAFF = "Teleportation, huh? Relics sure are full of surprises, naaa.",
		YELLOWAMULET = "It feels a little warm.. I wonder what it does.",
		GREENAMULET = "Conservation is important, nnaa.",
		SLURPERPELT = ".. Now I feel a little bad, nnaaaa..",	

		SLURPER = "Nnnaa, I'm not sure I like this thing.",
		SLURPER_PELT = ".. Now I feel a little bad, nnaaaa..",
		ARMORSLURPER = "Nnnaaa, it's all wet. What's the point of this thing anyway?",
		ORANGEAMULET = "Teleportation, huh? Relics sure are full of surprises, naaa.",
		YELLOWSTAFF = "I'm not sure how comfortable I am with carrying this thing around, nnaaa...",
		YELLOWGEM = "A yellow gem. Kinda looks valuable.",
		ORANGEGEM = "It's an orange gem. I wonder what I can use this for..",
		TELEBASE = 
		{
			VALID = "Looks like it's ready for use.",
			GEMS = "Nnaa.. Might need a few more gems first.",
		},
		GEMSOCKET = 
		{
			VALID = "Looks good to me.",
			GEMS = "Gems, gems, gems.",
		},
		STAFFLIGHT = "Seems dangerous. Should I really be near this thing?.. Nnaaa..",
		RESEARCHLAB4 = "Naa, I'm not even sure I can pronounce that.",
	
        ANCIENT_ALTAR = "Nna, this thing sure does look.. Important.",

        ANCIENT_ALTAR_BROKEN = "Certainly sinister, but not much else.",

        ANCIENT_STATUE = "I'd hate to meet whatever this was modeled after.",

        LICHEN = "Only a cyanobacteria could grow in this light.",
		CUTLICHEN = "Nutritious, but it won't last long.",

		CAVE_BANANA = "Any fruit is good fruit to me.",
		CAVE_BANANA_COOKED = "Nnnaa, it looks even better cooked.",
		CAVE_BANANA_TREE = "Looks kind of scary for a fruit tree..",
		ROCKY = "N-nnaa.. Maybe I shouldn't bother it..",
		
		COMPASS =
		{
			GENERIC="I can't get a reading.",
			N = "North",
			S = "South",
			E = "East",
			W = "West",
			NE = "Northeast",
			SE = "Southeast",
			NW = "Northwest",
			SW = "Southwest",
		},

		NIGHTMARE_TIMEPIECE =
		{
			WAXING = "H-hey, this thing's getting a little intense!",
			STEADY = "Seems ballanced, for the moment..",
			WANING = "It feels like it's diminishing.",
			DAWN = "I guess the nightmare is running out!",
			WARN = "I certainly feel something, nnnaa..",
			CALM = "It seems things are fine for now.",
			NOMAGIC = "Doesn't feel like there's any magic around here.",
		},

		HOUNDSTOOTH="The tooth of a hound. Pointy..",
		ARMORSNURTLESHELL="It sticks to my back.",
		BAT="A creature of the Abyss. This one isn't very friendly.",
		BATBAT = "This is way too heavy to fly with. But hitting something could be another story..",
		BATWING="Nnaa.. Might go nice in a stew..",
		BATWING_COOKED="H-hey, not bad!",
		BEDROLL_FURRY="Naa.. A nap on one of these sounds so nice right now..",
		BUNNYMAN="Poor thing. Nnaa.. I wonder if he's a hollow too.",
		FLOWER_CAVE="A nice natural alternative to fire.",
		FLOWER_CAVE_DOUBLE="A nice natural alternative to fire.",
		FLOWER_CAVE_TRIPLE="A nice natural alternative to fire.",
		GUANO="Gross, but it might just be useful.",
		LANTERN="Naa, I feel way safer around one of these. More than an open flame, anyway.",
		LIGHTBULB="I'd bet these things have tons of uses... Nnaa, I wonder how they taste.",
		MANRABBIT_TAIL="I'm not sure how comfortable I am with this, nnaaa..",
		MUSHTREE_TALL  ="I wasn't aware that mushrooms could even get this big.",
		MUSHTREE_MEDIUM="Oddly mesmerizing.",
		MUSHTREE_SMALL ="A mushroom. Or, is it a tree. Naa..",
		RABBITHOUSE="Nnaa, I feel at home already.",
		SLURTLE="These things sure do eat a lot, nnna.",
		SLURTLE_SHELLPIECES="Poor thing. First it's life, then it's home.",
		SLURTLEHAT="Nnna, I guess I could make more use of it than it's previous owner..",
		SLURTLEHOLE="I wonder what it looks like in there..",
		SLURTLESLIME="Like snot, but.. Not?",
		SNURTLE="The lesser of two snurtles, nnaa.",
		SPIDER_HIDER="Nnna! They get scarier and scarier!",
		SPIDER_SPITTER="I'd keep my distance, but I think that's what it wants, nnnaa.",
		SPIDERHOLE="Who knows what kinds of horrible things live in there, naaa..",
		STALAGMITE="A big pointy rock.",
		STALAGMITE_FULL="A big pointy rock.",
		STALAGMITE_LOW="A big pointy rock.",
		STALAGMITE_MED="A big pointy rock.",
		STALAGMITE_TALL="Pointy rocks sure are interesting, nnnaaa.",
		STALAGMITE_TALL_FULL="Pointy rocks sure are interesting, nnnaaa.",
		STALAGMITE_TALL_LOW="Rocks, rocks, rocks, rocks...",
		STALAGMITE_TALL_MED="Rocks, rocks, rocks, rocks...",

		TURF_CARPETFLOOR = "Yet another ground type.",
		TURF_CHECKERFLOOR = "Yet another ground type.",
		TURF_DIRT = "Yet another ground type.",
		TURF_FOREST = "Yet another ground type.",
		TURF_GRASS = "Yet another ground type.",
		TURF_MARSH = "Yet another ground type.",
		TURF_ROAD = "Yet another ground type.",
		TURF_ROCKY = "Yet another ground type.",
		TURF_SAVANNA = "Yet another ground type.",
		TURF_WOODFLOOR = "Yet another ground type.",

		TURF_CAVE="Yet another ground type.",
		TURF_FUNGUS="Yet another ground type.",
		TURF_SINKHOLE="Yet another ground type.",
		TURF_UNDERROCK="Yet another ground type.",
		TURF_MUD="Yet another ground type.",

		POWCAKE = "I guess it doesn't look that bad.. Na..",
        CAVE_ENTRANCE = 
        {
            GENERIC="I bet that rock can be broken.",
            OPEN = "Nnaaa, a familiar sight..",
        },
        CAVE_EXIT = "Maybe I could use a break, nnaaa..",
		MAXWELLPHONOGRAPH = "Music..? Strange.",
		BOOMERANG = "More than just a toy.",
		PIGGUARD = "Nnaa, maybe I shouldn't pick a fight with this one.",
		ABIGAIL = "N-naa, poor girl.",
		ADVENTURE_PORTAL = "Sinister. But I can't help but wonder what's inside.",
		AMULET = "It looks pretty, but does it have a use?..",
		ANIMAL_TRACK = "Tracks left by a koalefant. I sure am hungry..",
		ARMORGRASS = "Nna, I'm not really sure this is gonna protect me from anything..",
		ARMORMARBLE = "Maybe Reg should carry this one..",
		ARMORWOOD = "I feel invincible already.",
		ARMOR_SANITY = "I'm not sure if I even want this on me, naa..",
		ASH =
		{
			GENERIC = "There's a metaphor in here somewhere..",
			REMAINS_EYE_BONE = "The eyebone was consumed by fire when I teleported.",
			REMAINS_THINGIE = "This was once some thing before it got burned...",
		},
		AXE = "An axe. Lots of applications for this, I'm sure.",
		BABYBEEFALO = "Maybe just one pat.",
		BACKPACK = "This could come in handy.",
		BACONEGGS = "Simple. Yummy. That's all that really matters.",
		BANDAGE = "Standard for any Cave Raider.",
		BASALT = "N-nnaaa.. What kind of rock even is this? I can't break it!",
		BATBAT = "This is way too heavy to fly with. But hitting something could be another story..",
		BEARDHAIR = ".. Why am I holding onto this, nna.",
		BEDROLL_STRAW = "Well, it's not very comfy looking, but it'll do..",
		BEE =
		{
			GENERIC = "A bee. Cute, dangerous little things.",
			HELD = "Nnaa, this probably isn't safe..",
		},
		BEEBOX =
		{
			FULLHONEY = "Honey, honey, honey!",
			GENERIC = "There's some bees in here. I'd do well not to disturb them.",
			NOHONEY = "No honey for the moment.",
			SOMEHONEY = "Maybe I should wait a little longer..",
		},
		BEEFALO =
		{
			FOLLOWER = "I guess I can take you along with me.",
			GENERIC = "It's a beefalo.",
			NAKED = "Sorry mister Beefalo, I needed that fur.",
			SLEEPING = "They look so peaceful.",
		},
		BEEFALOHAT = "Nice and warm. Though I'm not sure why I'd need any more fur, nnaa..",
		BEEFALOWOOL = "Nice and warm. I bet I could make a few things out of this.",
		BEEHAT = "This should keep me from harms way.",
		BEEHIVE = "Full of bees. Maybe I avoid touching it.",
		BEEMINE = "Seems a little cruel, but, whatever works, naa.",
		BEEMINE_MAXWELL = "A big bottle of angry bloodsuckers. Nnaa, I'd hate to be on the recieving end of this.",
		BERRIES = "These ones look good for eating.",
		BERRIES_COOKED = "Oh boy. Mush.",
		BERRYBUSH =
		{
			BARREN = "It might need to be fertilized.",
			GENERIC = "These ones look good for eating.",
			PICKED = "Thanks for the food.",
		},
		BIRDCAGE =
		{
			GENERIC = "A birdcage. I bet Mitty would have liked this.",
			OCCUPIED = "Cute little thing. Maybe I should keep him for a little longer.",
			SLEEPING = "So peaceful.",
		},
		BIRDTRAP = "I'm sure I could catch something with is. Easy food.",
		BIRD_EGG = "It's an egg.",
		BIRD_EGG_COOKED = "Simple, healthy, delicious.",
		BISHOP = "Naa.. I don't like the look of that thing..",
		BLOWDART_FIRE = "Careful not to burn everything down.",
		BLOWDART_SLEEP = "A less lethal way of taking down, well, almost anything.",
		BLOWDART_PIPE = "This thing sure is primitive. Nnnaa, makes me wonder how effective it really is.",
		BLUEAMULET = "Why's it so cold?",
		BLUEGEM = "A blue gem. It makes me chilly just looking at it.",
		BLUEPRINT = "A blueprint. I wonder what it's for.",
		BLUE_CAP = "A blue capped mushroom. Looks pretty appetizing. ",
		BLUE_CAP_COOKED = "It's different now...",
		BLUE_MUSHROOM =
		{
			GENERIC = "It's a mushroom. A blue one.",
			INGROUND = "Looks like it's in the ground for now.",
			PICKED = "Nna, maybe it'll grow back.",
		},
		BOARDS = "Wooden boards. I bet I could make plenty of stuff with these.",
		BOAT = "Maybe that's how I got here.",
		BONESTEW = "Hey, not bad looking!",
		BUGNET = "I could collect all sorts of bugs with this.",
		BUSHHAT = "Nnna, the perfect disguise.",
		BUTTER = "Some butter. Now, what to make with it..",
		BUTTERFLY =
		{
			GENERIC = "Even pretty things like butterflies can exist in a place like this.",
			HELD = "Naaa, so pretty.",
		},
		BUTTERFLYMUFFIN = "Nnaa, sorry mister butterfly.",
		BUTTERFLYWINGS = "Sorry, I needed them more than you did.",
		CAMPFIRE =
		{
			EMBERS = "It's about to go out. Maybe I should find some more fuel.",
			GENERIC = "This might keep a few creatures away for the night.",
			HIGH = "N-nnaa, maybe I should stop feeding it.",
			LOW = "The fire's getting lower.",
			NORMAL = "The best way to keep warm in a place like this.",
			OUT = "Well, there it goes.",
		},
		CANE = "It makes walking seem much easier!",
		CARROT = "A carrot. Maybe just a nibble, nnaa.",
		CARROT_COOKED = "Nothing fancy, bit it'll do.",
		CARROT_PLANTED = "Now all I have to do is be patient.",
		CARROT_SEEDS = "A carrot farm sounds pretty nice.",
		CAVE_FERN = "An ordinary fern.",
		CHARCOAL = "So much excitement for something so.. Sad.",
        CHESSJUNK1 = "It looks like chess pieces. Strange.",
        CHESSJUNK2 = "More of them. Someone must really like chess.",
        CHESSJUNK3 = "What are all these even from?",
		CHESTER = "He looks kinda hungry.",
		CHESTER_EYEBONE =
		{
			GENERIC = "Nnaa, I feel like it's staring right at me.",
			WAITING = "Sleeping for now, I suppose.",
		},
		COOKEDMANDRAKE = "I suppose it's his fault for looking so tasty.",
		COOKEDMEAT = "Gotta keep my strength up somehow.",
		COOKEDMONSTERMEAT = "Gross, but it'll do.",
		COOKEDSMALLMEAT = "Just a bit of a snack.",
		COOKPOT =
		{
			COOKING_LONG = "It'll be a while before it's finished.",
			COOKING_SHORT = "Nnnaa, I'm getting hungry just thinking about it.",
			DONE = "Looks like it's done. Time to eat up!",
			EMPTY = "Maybe just a quick snack?..",
		},
		CORN = "High in fructose!",
		CORN_COOKED = "High in fructose!",
		CORN_SEEDS = "It's a seed.",
		CROW =
		{
			GENERIC = "Creepy!",
			HELD = "He's not very happy in there.",
		},
		CUTGRASS = "Cut grass, ready for arts and crafts.",
		CUTREEDS = "Cut reeds, ready for crafting and hobbying.",
		CUTSTONE = "I've made them seductively smooth.",
		DEADLYFEAST = "A most potent dish.",
		DEERCLOPS = "It's enormous!!",
		DEERCLOPS_EYEBALL = "This is really gross.",
		DEPLETED_GRASS =
		{
			GENERIC = "It's probably a tuft of grass.",
		},
		DEVTOOL = "Strange. It kinda smells like meat.",
		DEVTOOL_NODEV = "I'm not strong enough to wield it.",
		DIRTPILE = "Just a pile of dirt.",
		DIVININGROD =
		{
			COLD = "I'm getting something, but it's faint.",
			GENERIC = "A strange relic. I wonder if it could be used to locate something?",
			HOT = "N-nnaa! This thing sure is getting loud!",
			WARM = "I must be heading in the right direction.",
			WARMER = "I'm headed in the right direction.",
		},
		DIVININGRODBASE =
		{
			GENERIC = "I wonder what this is for...",
			READY = "Maybe it needs a charge key?",
			UNLOCKED = "Seems like it'll work now.",
		},
		DIVININGRODSTART = "A strange device, for sure.",
		DRAGONFRUIT = "An interesting fruit. I wonder how it tastes.",
		DRAGONFRUIT_COOKED = "Still looks pretty strange to me.",
		DRAGONFRUIT_SEEDS = "A seed. Maybe I can grow more of those fruit?",
		DRAGONPIE = "When all else fails, put it in a pie.",
		DRUMSTICK = "I'm tempted to take a bite right out of it.",
		DRUMSTICK_COOKED = "Now it's even even more enticing.",
		DUG_BERRYBUSH = "I should plant this somewhere.",
		DUG_GRASS = "I should plant this somewhere",
		DUG_MARSH_BUSH = "I should plant this somewhere.",
		DUG_SAPLING = "I should plant this somewhere.",
		DURIAN = "A very pointy fruit. Smells pretty bad too.",
		DURIAN_COOKED = "Cooking didn't make it much better.",
		DURIAN_SEEDS = "A smelly little seed.",
		EARMUFFSHAT = "I gotta keep my ears warm somehow.",
		EGGPLANT = "It doesn't look like an egg.",
		EGGPLANT_COOKED = "It's even less eggy.",
		EGGPLANT_SEEDS = "It's a seed.",
		EVERGREEN =
		{
			BURNING = "Kinda feels like a waste..",
			BURNT = "Well, better it than me.",
			CHOPPED = "Well, onto the next one..",
			GENERIC = "An evergreen tree. These things stay pretty all year round.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "Kinda feels like a waste..",
			BURNT = "Well, better it than me.",
			CHOPPED = "Well, onto the next one..",
			GENERIC = "This evergreen looks a little lumpier than usual.",
		},
		EYEPLANT = "Is something observing me?..",
		FARMPLOT =
		{
			GENERIC = "Maybe I should grow some food.",
			GROWING = "Nnaa, can't grow any faster?",
			NEEDSFERTILIZER = "It might need to be fertilized.",
		},
		FEATHERHAT = "I look ridiculous.",
		FEATHER_CROW = "A feather from a crow..",
		FEATHER_ROBIN = "A feather from a robin..",
		FEATHER_ROBIN_WINTER = "A feather from a winter bird.",
		FEM_PUPPET = "It looks like she's stuck.",
		FIREFLIES =
		{
			GENERIC = "So pretty. I wonder if I can catch them.",
			HELD = "Naaa, they glow so brightly!",
		},
		FIREHOUND = "That hound looks a bit more dangerous then usual..",
		FIREPIT =
		{
			EMBERS = "It's about to go out. Maybe I should find some more fuel.",
			GENERIC = "This might keep a few creatures away for the night.",
			HIGH = "N-nnaa, maybe I should stop feeding it.",
			LOW = "The fire's getting lower.",
			NORMAL = "The best way to keep warm in a place like this.",
			OUT = "Well, there it goes.",
		},
		FIRESTAFF = "I'm not sure how safe it is for me to be holding this thing.",

		FISH = "I bet I could make some killer stew with this..",
		FISHINGROD = "Perfect for, well, fishing.",
		FISHSTICKS = "Fishy, sticky. Delicious.",
		FISHTACOS = "Nnaa, smells fishy.",
		FISH_COOKED = "Grilled to perfection.",
		FLINT = "Ponty. Perfect for making tools.",
		FLOWER = "Both pretty, and useful.",
		FLOWERHAT = "So pretty.",
		FLOWER_EVIL = "This flower sure does look sinister.",
		FOLIAGE = "Just a bunch of plants.",
		FOOTBALLHAT = "Nnnaa, what a strange helmet.",
		FROG =
		{
			DEAD = "Ribbit, ribbit..",
			GENERIC = "A frog! And a grumpy one at that.",
			SLEEPING = "Sleep tight, froggy.",
		},
		FROGGLEBUNWICH = "Well, bad food is better than no food.",
		FROGLEGS = "I'm sure I could use these for- Something..",
		FROGLEGS_COOKED = "Hey, these aren't so bad after all.",
		FRUITMEDLEY = "I cooked it myself!",
		GEARS = "A bunch of ancient technology.",
		GHOST = "Poor soul.",
		GOLDENAXE = "That's one expensive axe.",
		GOLDENPICKAXE = "Seems a little impracticle.",
		GOLDENPITCHFORK = "What's the point of the gold part anyway?",
		GOLDENSHOVEL = "I can't wait to dig holes.",
		GOLDNUGGET = "Sure does look expensive.",
		GRASS =
		{
			BARREN = "Looks like it needs to grow back first.",
			BURNING = "So long, grass.",
			GENERIC = "It's a tuft of nice soft grass.",
			PICKED = "It looks so sad now.",
		},
		GREEN_CAP = "Naaaa.. Just thinking about eating this worries me.",
		GREEN_CAP_COOKED = "This doesn't look half bad now.",
		GREEN_MUSHROOM =
		{
			GENERIC = "A nice green mushroom.",
			INGROUND = "Maybe I should come back at dusk.",
			PICKED = "I wonder if it will grow back?",
		},
		GUNPOWDER = "Perfect for causing explosions.",
		HAMBAT = "What a waste of food.",
		HAMMER = "A hammer. Useful for.. Hammering.",
		HEALINGSALVE = "Nnnaa.. It kinda stings, but it will do.",
		HEATROCK =
		{
			COLD = "It's cold to the touch.",
			GENERIC = "I'm sure some fire would heat it up.",
			HOT = "Nnnaaa, nice and hot~",
			WARM = "The rock's all warm now!",
		},
		HOME = "I wonder if anyone's home?",
		HOMESIGN = "The sign reads \"You are here\"",
		HONEY = "Sweet, sweet honey.",
		HONEYCOMB = "Bees sure are efficient. ",
		HONEYHAM = "A nice sweet ham. I can't wait to chow down!",
		HONEYNUGGETS = "Some sweet nuggets. Perfect for a quick bite.",
		HORN = "This thing sure is loud.",
		HOUND = "Nnna, not a fan of these things.",
		HOUNDBONE = "Creepy.",
		HOUNDMOUND = "I wouldn't want to pick a bone with the owner.",
		ICEBOX = "A perfect place to store some food.",
		ICEHOUND = "Another hound? Nnaaa.. Looking at it is giving me chills.",
		INSANITYROCK =
		{
			ACTIVE = "Take that, sane self.",
			INACTIVE = "Huh. It's lowered into the ground?",
		},
		JAMMYPRESERVES = "Now if only I had something to put it on.",
		KABOBS = "I guess food's even better when it's on a stick.",
		KILLERBEE =
		{
			GENERIC = "Oh no! It's a killer bee!",
			HELD = "This seems dangerous.",
		},
		KNIGHT = "Some kind of.. Horse?",
		KOALEFANT_SUMMER = "That thing sure does look tasty.",
		KOALEFANT_WINTER = "It looks warm. Not to mention, tasty.",
		KRAMPUS = "Nnnaaa, hey! Stay away from my stuff!",
		KRAMPUS_SACK = "It's surprisingly light.",
		LEIF = "Is that.. A tree? Nnnaaa...",
		LEIF_SPARSE = "Is that.. A tree?",
		LIGHTNING_ROD =
		{
			CHARGED = "Looks like it's charged.",
			GENERIC = "A rod that shoots lightning? Don't mind if I do.",
		},
		LITTLE_WALRUS = "Hey there, little guy.",
		LIVINGLOG = "I feel like it's staring back at me, with judging eyes.",
		LOCKEDWES = "Maxwell's statues are trapping him. Maybe I should help out.",
		LOG =
		{
			BURNING = "A burning log!",
			GENERIC = "I'm not sure I could lift something that big. That's a lot of wood.",
		},
		LUREPLANT = "There's something oddly alluring about it.",
		LUREPLANTBULB = "Now I can start my very own meat farm.",
		MALE_PUPPET = "It looks like he's trapped.",
		MANDRAKE =
		{
			DEAD = "That thing sure was creepy.",
			GENERIC = "That's one strange looking plant.",
			PICKED = "Hey, get out of here, quit following me!",
		},
		MANDRAKESOUP = "Nnaa, your fault for being so tasty looking.",
		MANDRAKE_COOKED = "It doesn't seem so strange anymore.",
		MARBLE = "Fancy.",
		MARBLEPILLAR = "I think I could use that.",
		MARBLETREE = "I'm not sure if an axe is strong enough to cut that.",
		MARSH_BUSH =
		{
			BURNING = "Nnnaa, it's burning fast!",
			GENERIC = "That looks like it'd hurt.",
			PICKED = "Well that wasn't worth it at all.",
		},
		MARSH_PLANT = "It's a plant.",
		MARSH_TREE =
		{
			BURNING = "It's burning!",
			BURNT = "Now it's burnt and spiky.",
			CHOPPED = "Onto the next one.",
			GENERIC = "That's one spiky tree.",
		},
		MAXWELL = "Nnaa, I don't trust him at all.",
		MAXWELLHEAD = "You'd have to be really full of yourself to build something like this.",
		MAXWELLLIGHT = "Could it be activated my motion?",
		MAXWELLLOCK = "A keyhole? But where's the key?",
		MAXWELLTHRONE = "Being in it's presence makes me feel uncomfortable, nnnaa..",
		MEAT = "Plain old meat. There's so many possibilities.",
		MEATBALLS = "Simple, but yummy.",
		MEATRACK =
		{
			DONE = "Looks like the meat is done drying.",
			DRYING = "Maybe I should give it some more time.",
			GENERIC = "Perfect for drying all kinds of meats.",
		},
		MEAT_DRIED = "Perfect for long excursions.",
		MERM = "Nnnaa, something smells.",
		MERMHEAD = "The stinkiest thing I'll smell all day.",
		MERMHOUSE = "What a strange choice for a home.",
		MINERHAT = "Hands free lighting, with a little bonus protection.",
		MONKEY = "Curious little guy.",
		MONKEYBARREL = "N-nnaa, did that thing just move?",
		MONSTERLASAGNA = "It looks pretty good, for what it is..",
		MONSTERMEAT = "It smells kind of rancid.",
		MONSTERMEAT_DRIED = "Looks like ordinary jerky to me. Though the smell gives it away.",
		MOSQUITO =
		{
			GENERIC = "Disgusting little insects.",
			HELD = "Looks like your blood-sucking days are over.",
		},
		MOSQUITOSACK = "It's full of blood.",
		MOUND =
		{
			DUG = "Well now I feel a bit bad.",
			GENERIC = "There could be something down there. But is it worth it?",
		},
		NIGHTLIGHT = "A light. An unsettling one at that.",
		NIGHTMAREFUEL = "Nnna.. Just looking at it makes me nervous.",
		NIGHTSWORD = "I can feel the fear pouring from it.",
		NITRE = "A strange type of rock. I wonder what I can do with it?",
		ONEMANBAND = "Well this just feels silly.",
		PANDORASCHEST = "Who knows what's inside?",
		PANFLUTE = "I can serenade the animals.",
		PAPYRUS = "A sheet of paper. I bet I can write a few lists with this.",
		PENGUIN = "They look so defenseless.",
		PERD = "N-nnaa, give back my berries, dumb bird!",
		PEROGIES = "I cooked them myself!",
		PETALS = "I destroyed a defenseless flower for these. But what do I use them for?",
		PETALS_EVIL = "Nnaaa.. Holding these makes my head hurt.",
		PHLEGM = "Gross..",
		PICKAXE = "I can break all kinds of rocks with this.",
		PIGGYBACK = "Seems a bit morbid. But at least I can carry more things with it.",
		PIGHEAD = "Who could have done something like this?",
		PIGHOUSE =
		{
			FULL = "I can see a snout pressed up against the window.",
			GENERIC = "That's a pretty nice house, for a pig.",
			LIGHTSOUT = "Looks like I scared him off.",
		},
		PIGKING = "This is their king? Nnnaa, he smells..",
		PIGMAN =
		{
			DEAD = "Poor thing.",
			FOLLOWER = "Nnaa, I suppose we're friends now.",
			GENERIC = "They kind of smell, but they mean no harm.",
			GUARD = "Maybe I should leave him be.",
			WEREPIG = "I don't think that one is friendly.",
		},
		PIGSKIN = "What was the point of this again?",
		PIGTENT = "It's somewhere safe to sleep, I guess.",
		PIGTORCH = "It's a bunch of pig heads stacked onto eachother. Fancy.",
		PINECONE = 
		{
		    GENERIC = "Soon, you'll be a big tall tree.",
		    PLANTED = "It'll take a while for it to grow.",
		},
		PITCHFORK = "Useful for roughing up entire plots of land.",
		PLANTMEAT = "How can a leaf be this meaty?",
		PLANTMEAT_COOKED = "Well, now it looks a bit more appetizing at least.",
		PLANT_NORMAL =
		{
			GENERIC = "An ordinary plant.",
			GROWING = "It's growing, but it might take a while.",
			READY = "It looks like it's ready to harvest.",
		},
		POMEGRANATE = "A tasty pomegranate.",
		POMEGRANATE_COOKED = "It looks even better when it's cooked.",
		POMEGRANATE_SEEDS = "It's a pomegranate seed.",
		POND = "Small, but surprisingly deep.",
		POOP = "Good for making your plants grow strong.",
		PUMPKIN = "That's a big pumpkin.",
		PUMPKINCOOKIE = "I made them myself.",
		PUMPKIN_COOKED = "Nothing tastier than a roasted pumpkin.",
		PUMPKIN_LANTERN = "An eerie decoration.",
		PUMPKIN_SEEDS = "It's a pumpkin seed. I bet I could plant more.",
		PURPLEAMULET = "I can hear voices in my head when I hold it too close.",
		PURPLEGEM = "A purple gem. It's almost mesmerizing.",
		RABBIT =
		{
			GENERIC = "Nnna, he looks a lot like me.",
			HELD = "Poor thing. It's shaking.",
		},
		RABBITHOLE = "I wonder where it leads?",
		RAINOMETER = "This device should tell me the weather.",
		RATATOUILLE = "Fancy and yummy, all at once.",
		RAZOR = "I might need more than one, if this is meant for me.",
		REDGEM = "A red gem. It feels warm.",
		RED_CAP = "I bet it'd fill me right up. Though it doesn't look very healthy.",
		RED_CAP_COOKED = "Maybe I shouldn't eat it now.",
		RED_MUSHROOM =
		{
			GENERIC = "It's a red mushroom.",
			INGROUND = "Looks like it's gone for now.",
			PICKED = "I wonder if it will grow back.",
		},
		REEDS =
		{
			BURNING = "That's really burning.",
			GENERIC = "It's a clump of reeds.",
			PICKED = "I picked all the useful reeds.",
		},
        RELIC = 
        {
            GENERIC = "A relic. I'm sure a Cave Raider would be all over this.",
            BROKEN = "Nothing to work with here.",
        },
        RUINS_RUBBLE = "Maybe I can fix it up?",
        RUBBLE = "A pile of rubble. Not much to it.",
		RESEARCHLAB = "A strange, science-y machine. I can make all kinds of things with it.",
		RESEARCHLAB2 = "This one looks a bit more complicated.",
		RESEARCHLAB3 = "It looks more like a relic, than an object of science.",
		RESEARCHLAB4 = "It's- A hat. On a box. With a lever.",
		RESURRECTIONSTATUE = "Close enough.",
		RESURRECTIONSTONE = "It looks scary, but I can't help but feel calm around it.",
		ROBIN =
		{
			GENERIC = "It looks so carefree. Mitty would love it.",
			HELD = "It's surprisingly calm.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "I guess not all things disappear during the winter.",
			HELD = "Naa.. It feels soft, and warm.",
		},
		ROBOT_PUPPET = "It's trapped.",
		ROCK_LIGHT =
		{
			GENERIC = "Looks like this lava pit is crusted over.",
			OUT = "It's like it can break at any time.",
			LOW = "The lava's crusting over.",
			NORMAL = "Comfy.",
		},
		ROCK = "A big rock. I wonder if I can break it.",
		ROCKS = "Rocks of varying shapes and sizes.",
        ROOK = "A creature made of metal?",
		ROPE = "Some bits of rope.",
		ROTTENEGG = "The odor on this is almost unbearable.",
		SANITYROCK =
		{
			ACTIVE = "Nnaa.. That's one unsettling rock.",
			INACTIVE = "Could it be underground?",
		},
		SAPLING =
		{
			BURNING = "An easy target for a forest fire.",
			GENERIC = "Soon it will grow big and strong.",
			PICKED = "That'll teach him.",
		},
		SEEDS = "All these seeds, and nothing to do with them.",
		SEEDS_COOKED = "It's barely food, but it's better than nothing.",
		SEWING_KIT = "Now what to sew with it?..",
		SHOVEL = "Who knows what kind of mysteries I could dig up.",
		SILK = "It feels nice and soft.",
		SKELETON = "Another soul returns to the abyss.",
		SKULLCHEST = "An ominous container for ominous goods.",
		SMALLBIRD =
		{
			GENERIC = "What a tiny bird.",
			HUNGRY = "I think it might be hungry.",
			STARVING = "Poor thing, it looks like it's starving.",
		},
		SMALLMEAT = "Some meat from a small animal. I can't help but feel sorry for it.",
		SMALLMEAT_DRIED = "Really small jerky.",
		SPAT = "That thing could use a bath.",
		SPEAR = "A rock on a stick. There's not much to it, but it works.",
		SPIDER =
		{
			DEAD = "Nnaaa, good riddance.",
			GENERIC = "So creepy and crawly..",
			SLEEPING = "I'd better not be here when he wakes up.",
		},
		SPIDERDEN = "I guess that's where they're all coming from.",
		SPIDEREGGSACK = "Please don't hatch, please don't hatch.",
		SPIDERGLAND = "It smells..",
		SPIDERHAT = "Nnnaa, gross..",
		SPIDERQUEEN = "N-nnaaa, that spider's a little big for my tastes.",
		SPIDER_WARRIOR =
		{
			DEAD = "And stay dead!",
			GENERIC = "Naaa, I don't like the look of that one.",
			SLEEPING = "I should stay quiet..",
		},
		SPOILED_FOOD = "Maybe I shouldn't eat that..",
		STATUEHARP = "Nna, where'd the head go?",
		STATUEMAXWELL = "Compensating much?",
		STEELWOOL = "A big ball of metal fiber. What's the point of this anyway?",
		STINGER = "Ow, pointy.",
		STRAWHAT = "Looks a little tacky.",
		STUFFEDEGGPLANT = "I can't wait to dig in!",
		SUNKBOAT = "Well, that boat won't be going anywehre.",
		SWEATERVEST = "Looks comfy.",
		TAFFY = "Chewy.",
		TALLBIRD = "That bird sure is tall.",
		TALLBIRDEGG = "I wonder if it'll hatch.",
		TALLBIRDEGG_COOKED = "Delicious~",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "Maybe I should warm it up a little.",
			GENERIC = "Nn-nnaaa! I think it's hatching!",
			HOT = "It's getting a little hot. Maybe I can cool it off a little?",
			LONG = "It'll be a while before it's time to hatch.",
			SHORT = "It should hatch any time now.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "That egg sure does look tasty..",
			PICKED = "I'll be back for more.",
		},
		TEENBIRD =
		{
			GENERIC = "A juvinile tallbird.",
			HUNGRY = "Hey little guy, you hungry?",
			STARVING = "It doesn't look very happy to see me..",
		},
		TELEBASE =
		{
			VALID = "Looks like it's ready.",
			GEMS = "It needs more purple gems to work.",
		},
		GEMSOCKET = 
		{
			VALID = "Looks like it's ready.",
			GEMS = "It needs a gem.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "Where will this thing take me?",
			GENERIC = "Some kind of portal?",
			LOCKED = "I don't think it's ready just yet..",
			PARTIAL = "Hey, I think I'm getting somewhere.",
		},
		TELEPORTATO_BOX = "A.. Box? What Could this be?",
		TELEPORTATO_CRANK = "Tough enough to handle the most intense use.",
		TELEPORTATO_POTATO = "How do you grow a potato made from metal?",
		TELEPORTATO_RING = "Some kind of ring.",
		TELESTAFF = "It can show me the world.",
		TENT = "Finally, a comfy place to sleep.",
		TENTACLE = "A tentacle from the ground? Looks dangerous.",
		TENTACLESPIKE = "It's pointy and slimy.",
		TENTACLESPOTS = "What's this supposed to be?",
		TENTACLE_PILLAR = "A big slimy pole.",
		TENTACLE_PILLAR_ARM = "Little slippery arms.",
		TENTACLE_GARDEN = "Yet another slimy pole.",
		TOPHAT = "Fancy.",
		TORCH = "A Cave Raider's best friend.",
		TRAP = "This should do the trick.",
		TRAP_TEETH = "Those look awfully nasty.",
		TRAP_TEETH_MAXWELL = "I should avoid stepping on that.",
		TREASURECHEST = "I wonder what's inside?",
		TREASURECHEST_TRAP = "I bet there's all sorts of useful things in there.",
		TREECLUMP = "These trees are blocking my path.",
		TRINKET_1 = "What is this even for? It's like a glorified rock.",
		TRINKET_10 = "Morbid.",
		TRINKET_11 = "Everything this thing tells me smells fishy.",
		TRINKET_12 = "What's this doing in there?..",
		TRINKET_13 = "Looks like some kind of container.",
		TRINKET_2 = "Some kind of instrument? It doesn't even work!",
		TRINKET_3 = "Nnaaa, what's with this thing? I can't seem to untie it.",
		TRINKET_4 = "A weird little statue. I wonder who it's modeled after?",
		TRINKET_5 = "What kind of device could this be?",
		TRINKET_6 = "Well, I can't do much with these.",
		TRINKET_7 = "I have no time for fun and games.",
		TRINKET_8 = "A plug for a tub? Where does this stuff even come from? ",
		TRINKET_9 = "Buttons? I wonder what these came off of.",
		TRUNKVEST_SUMMER = "I shouldn't burn up in this.",
		TRUNKVEST_WINTER = "This should keep me nice and warm, nnnaaa~",
		TRUNK_COOKED = "Hey, doesn't look half bad!",
		TRUNK_SUMMER = "A light breezy trunk.",
		TRUNK_WINTER = "This trunk has tons of hair on it. Maybe to keep warm.",
		TURF_CARPETFLOOR = "It's surprisingly scratchy.",
		TURF_CHECKERFLOOR = "These are pretty snazzy.",
		TURF_DIRT = "A chunk of ground.",
		TURF_FOREST = "A chunk of ground.",
		TURF_GRASS = "A chunk of ground.",
		TURF_MARSH = "A chunk of ground.",
		TURF_ROAD = "Hastily cobbled stones.",
		TURF_ROCKY = "A chunk of ground.",
		TURF_SAVANNA = "A chunk of ground.",
		TURF_WOODFLOOR = "These are floorboards.",
		TURKEYDINNER = "I sure am feeling hungry, looking at this.",
		TWIGS = "Some twigs. Now what to make with them...",
		UMBRELLA = "Hey, an umbrella! It should keep my fur nice and dry.",
		UNIMPLEMENTED = "It doesn't look finished! It could be dangerous.",
		WAFFLES = "The perfect snack.",
		WALL_HAY = "This isn't gonna last very long.",
		WALL_HAY_ITEM = "What's this going to stop?",
		WALL_STONE = "I feel safer already.",
		WALL_STONE_ITEM = "This wall should be pretty sturdy.",
		WALL_RUINS = "An ancient piece of wall.",
		WALL_RUINS_ITEM = "Old, but sturdy.",
		WALL_WOOD = "Back to basics.",
		WALL_WOOD_ITEM = "Better than grass, at least.",
		WALL_MOONROCK = "This wall is made out of strange material.",
		WALL_MOONROCK_ITEM = "Very light but surprisingly sturdy.",
		WALRUS = "A walrus? I've never seen one up close like this before.",
		WALRUSHAT = "Nnaaa, why's this thing so prickly?",
		WALRUS_CAMP =
		{
			EMPTY = "Looks like somebody was camping here. Doesn't look like they're here anymore.",
			GENERIC = "It looks warm and cozy inside.",
		},
		WALRUS_TUSK = "I'm sure I'll find a use for it eventually.",
		WARG = "This one looks like an alpha. Nnnnaa, maybe I should keep my distance.",
		WASPHIVE = "These ones don't look very happy.",
		WETGOOP = "Good enough, I guess.",
		WINTERHAT = "A nice warm hat, useful during winter in particular.",
		WINTEROMETER = "A needlessly large thermometer.",
		WORMHOLE =
		{
			GENERIC = "A hole?.. A hungry hole, at that.",
			OPEN = "Maybe I should see what's inside.",
		},
		WORMHOLE_LIMITED = "Nnnaa, this one looks a little strange.",
		ACCOMPLISHMENT_SHRINE = "Looking at it makes me feel fufilled.",        
		LIVINGTREE = "I feel like I'm being watched.",
		ICESTAFF = "This staff is kind of cold. I wonder what it does?",
		REVIVER = "A makeshift heart. I hope this thing works..",
		LIFEINJECTOR = "Nnaa, better already.",
		SKELETON_PLAYER =
		{
			MALE = "%s died by being hurt by %s. Poor soul.",
			FEMALE = "%s died by being hurt by %s. Poor soul.",
			ROBOT = "%s died by being hurt by %s. Poor soul.",
			DEFAULT = "%s died by being hurt by %s. Poor soul.",
		},
		HUMANMEAT = "I'm not sure about this..",
		HUMANMEAT_COOKED = "Cooking it didn't really make it look better, naaa..",
		HUMANMEAT_DRIED = "Human Meat. But dried. It still sickens me, though..",
		MOONROCKNUGGET = "A strange rock?.. I wonder where it came from.",
	},
	DESCRIBE_GENERIC = "It's a thing, that's for sure.",
	DESCRIBE_TOODARK = "Nnaaa, I can't see a thing.",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Shouldn't the egg be tall, too?",
	},
}
